name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/ml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure CLI login
        run: |
          azd auth login
          az login

      - name: Set environment variables
        run: echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Deploy with azd
        run: azd up
