name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install Azure Developer CLI (azd)
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
          echo "$HOME/.azure-dev/bin" >> $GITHUB_PATH  # Ensure azd is in PATH

      - name: Debug Azure Environment Variables
        run: |
          echo "AZURE_TENANT_ID: $AZURE_TENANT_ID"
          echo "AZURE_CLIENT_ID: $AZURE_CLIENT_ID"
          echo "AZURE_CLIENT_SECRET: (hidden)"
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Azure CLI Login using Service Principal
        run: |
          az login --service-principal \
            --username="${{ secrets.AZURE_CLIENT_ID }}" \
            --password="${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant="${{ secrets.AZURE_TENANT_ID }}"

      - name: Set Azure Subscription
        run: |
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          echo "Using Subscription: $(az account show --query 'name' -o tsv)"

      - name: Authenticate with Azure Developer CLI (azd)
        run: |
          azd auth login \
            --client-id "${{ secrets.AZURE_CLIENT_ID }}" \
            --client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant-id "${{ secrets.AZURE_TENANT_ID }}"

      - name: Initialize Azure Developer CLI Environment
        run: |
          azd env new sandbox --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Deploy with azd
        run: azd down
